### ISSUE TITLE
re: obsolete How To's

### ISSUE THREAD

**Issue by forresthayes** [redwoodjs/awesome-redwood#12]
Now that RedwoodJS has docs for [Authentication](https://redwoodjs.com/docs/authentication) and  [adding Tailwind CSS](https://redwoodjs.com/docs/cli-commands#tailwind), should we remove or mark as obsolete/legacy the related items in the awesome [How To's](https://github.com/redwoodjs/awesome-redwood#how-tos) section?

**Comment by thedavidprice** [comment]
Agreed it's better to update with the latest. But I personally like the idea of leaving a trail/history. There's still some goodness in those examples (as well as people who contributed), so I'm not in favor of simple deletion. Is there a standard practice here for "awesome repo" projects?

How about:
- strikethrough of old with the addition of new
...or...
- sub-bullet with note/addition of new
..or...
- combination of above

Definitely open to ideas and more discussion.

**Comment by ajcwebdev** [comment]
Hey Forrest, thanks for the input, I saw the same issues when I did a big rewrite of the repo in October and addressed all that so I'm going to close this out.
